[package]
name = "simple-yaml-parser"
version = "0.0.0"
edition = "2024"
description = "No allocation YAML key value parser with comment support"
authors = ["Ben <kaleidawave@gmail.com>"]
license = "MIT"
keywords = ["yaml", "yml"]
categories = ["parser-implementations"]
repository = "https://github.com/kaleidawave/simple-yaml-parser"

[lib]
path = "lib.rs"

[lints.clippy]
pedantic = "deny"

# [[test]]
# path = "tests/specification.rs"
# harness = false

[package.metadata.scripts]
defaults.file = 'private/corpus/aaa.yaml'

test = 'spectra test specification.md "cargo r --example parse -q -- --rpc --interactive"'
run = 'cargo r --example parse -- $file'
